### ISSUE TITLE
整体进度（校对）

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/cython-doc-zh#1]
| 章节 | 贡献者 | 进度 |
| --- | --- | --- |
| [Cython - 概述](https://github.com/apachecn/cython-doc-zh/blob/master/docs/3.md) | @varyshare,@runzhi214  | 100% |
| [安装 Cython](https://github.com/apachecn/cython-doc-zh/blob/master/docs/4.md) | @varyshare,@runzhi214  | 100% |
| [构建 Cython 代码](https://github.com/apachecn/cython-doc-zh/blob/master/docs/5.md) | @varyshare,@runzhi214 | 100% |
| [通过静态类型更快的代码](https://github.com/apachecn/cython-doc-zh/blob/master/docs/6.md) | @varyshare,@runzhi214  | 100% |
| [基础教程](https://github.com/apachecn/cython-doc-zh/blob/master/docs/8.md) | @varyshare,@runzhi214  | 100% |
| [调用 C 函数](https://github.com/apachecn/cython-doc-zh/blob/master/docs/9.md) | @varyshare,@runzhi214  | 100% |
| [使用 C 库](https://github.com/apachecn/cython-doc-zh/blob/master/docs/10.md) | @varyshare,@runzhi214  | 100% |
| [扩展类型（又名.cdef 类）](https://github.com/apachecn/cython-doc-zh/blob/master/docs/11.md) | @runzhi214 | 100% |
| [pxd 文件](https://github.com/apachecn/cython-doc-zh/blob/master/docs/12.md) | @runzhi214 | 100% |
| [Caveats](https://github.com/apachecn/cython-doc-zh/blob/master/docs/13.md) | @runzhi214 | 100% |
| [Profiling](https://github.com/apachecn/cython-doc-zh/blob/master/docs/14.md) | @runzhi214 | 100% |
| [Unicode 和传递字符串](https://github.com/apachecn/cython-doc-zh/blob/master/docs/15.md) | @runzhi214 | 100% |
| [内存分配](https://github.com/apachecn/cython-doc-zh/blob/master/docs/16.md) | @runzhi214 | 100% |
| [在C/C ++程序中内嵌Cython模块](https://github.com/apachecn/cython-doc-zh/blob/master/docs/17.md) | @runzhi214 | 100% |
| [纯 Python 模式](https://github.com/apachecn/cython-doc-zh/blob/master/docs/17.md) | @runzhi214 | 100% |
| [使用 NumPy](https://github.com/apachecn/cython-doc-zh/blob/master/docs/18.md) | @runzhi214 | 100% |
| [使用 Python 数组](https://github.com/apachecn/cython-doc-zh/blob/master/docs/19.md) | @runzhi214 | 100% |
| [用Cython写并行代码](https://github.com/apachecn/cython-doc-zh/blob/master/docs/42.md) | @runzhi214 | 100% |
| [进一步阅读](https://github.com/apachecn/cython-doc-zh/blob/master/docs/20.md) | @runzhi214 | 100% |
| [相关工作](https://github.com/apachecn/cython-doc-zh/blob/master/docs/21.md) | @runzhi214 | 100% |
| [附录：在 Windows 上安装 MinGW](https://github.com/apachecn/cython-doc-zh/blob/master/docs/22.md) | @runzhi214 | 100% |
| [语言基础](https://github.com/apachecn/cython-doc-zh/blob/master/docs/24.md) | @runzhi214 | 100% |
| [扩展类型](https://github.com/apachecn/cython-doc-zh/blob/master/docs/25.md) | @runzhi214 | 100% |
| [扩展类型的特殊方法](https://github.com/apachecn/cython-doc-zh/blob/master/docs/26.md) | @runzhi214 | 100% |
| [在 Cython 模块之间共享声明](https://github.com/apachecn/cython-doc-zh/blob/master/docs/27.md) | @runzhi214 | 100% |
| [与外部 C 代码连接](https://github.com/apachecn/cython-doc-zh/blob/master/docs/28.md) | @runzhi214 | 100% |
| [源文件和编译](https://github.com/apachecn/cython-doc-zh/blob/master/docs/29.md) | @runzhi214 | 100% |
| [早期绑定速度](https://github.com/apachecn/cython-doc-zh/blob/master/docs/30.md) | @runzhi214 | 100% |
| [在 Cython 中使用 C ++](https://github.com/apachecn/cython-doc-zh/blob/master/docs/31.md) | @runzhi214 | 100% |
| [融合类型（模板）](https://github.com/apachecn/cython-doc-zh/blob/master/docs/32.md) | @runzhi214 | 100% |
| [将 Cython 代码移植到 PyPy](https://github.com/apachecn/cython-doc-zh/blob/master/docs/33.md) | @runzhi214 | 100% |
| [从Cython0.29迁移到3.0](https://github.com/apachecn/cython-doc-zh/blob/master/docs/43.md) | @runzhi214 | 100% |
| [Limitations](https://github.com/apachecn/cython-doc-zh/blob/master/docs/34.md) | @runzhi214 | 100% |
| [Cython 和 Pyrex 之间的区别](https://github.com/apachecn/cython-doc-zh/blob/master/docs/35.md) | @runzhi214 | 100% |
| [类型化的内存视图](https://github.com/apachecn/cython-doc-zh/blob/master/docs/36.md) | @runzhi214 | 100% |
| [实现缓冲协议](https://github.com/apachecn/cython-doc-zh/blob/master/docs/37.md) | @runzhi214 | 100% |
| [使用并行性](https://github.com/apachecn/cython-doc-zh/blob/master/docs/38.md) | @runzhi214 | 100% |
| [调试你的 Cython 程序](https://github.com/apachecn/cython-doc-zh/blob/master/docs/39.md) | @runzhi214 | 100% |
| [用于 NumPy 用户的 Cython](https://github.com/apachecn/cython-doc-zh/blob/master/docs/40.md) | @runzhi214 | 100% |
| [Pythran 作为 Numpy 后端](https://github.com/apachecn/cython-doc-zh/blob/master/docs/41.md) | @runzhi214 | 100% |
| [Cython和GIL](https://github.com/apachecn/cython-doc-zh/blob/master/docs/44.md) | @runzhi214 | 100% |
| [Troubleshooting](https://github.com/apachecn/cython-doc-zh/blob/master/docs/45.md) | @runzhi214 | 100% |
| [FAQ](https://github.com/apachecn/cython-doc-zh/blob/master/docs/46.md) | @runzhi214 | 100% |

**Comment by varyshare** [comment]
认领：
- [x] Cython - 概述 
- [x] 安装 Cython 
- [x] 构建 Cython 代码
- [x] 通过静态类型更快的代码
- [x] 基础教程
- [x] 调用 C 函数 
- [x] 使用 C 库

QQ：2447512227

**Comment by wizardforcel** [comment]
@varyshare 请加快速度

**Comment by runzhi214** [comment]
全部认领
deadline：2023年12月31日前

**Comment by runzhi214** [comment]
截止到目前为止，文档全部翻译完成

**Comment by jiangzhonglian** [comment]
辛苦了，私聊一下我QQ：529815144
